### ISSUE TITLE
Pls add encrypt option

### ISSUE THREAD

**Issue by mohitjoshi155** [MasterBrian99/GDrive-efc#3]
No encrypt option available
Pls add it if u can

**Comment by MasterBrian99** [comment]
https://anadius.github.io/gd-efc/build.html

**Comment by skullle** [comment]
Is there any simpler way that you can add the encrypt option in the repo itself?

**Comment by MasterBrian99** [comment]
> No encrypt option available
> Pls add it if u can

Done !.Thank you for letting me know..

**Comment by MasterBrian99** [comment]
> Is there any simpler way that you can add the encrypt option in the repo itself?

i already add Encrypt Option..
