### ISSUE TITLE
Folder Copy

### ISSUE THREAD

**Issue by b06357-redlands** [MasterBrian99/GDrive-efc#7]
This is amazing reworked of the original tool, and is awesome.

However we are not able to **select and Copy** folders, it would be an awesome feature if implemented.

Shared drive creation websites are awesome too, there is another one that has few more https://td.hackgence.com

**Comment by MasterBrian99** [comment]
Thank you, I really appreciate you taking the time to express that.
Actually i can't make many changes 'cause [main.js](https://github.com/MasterBrian99/GDrive-efc/blob/master/main.obf.js) were obfuscated. visit these links[1](https://github.com/anadius/gd-efc/issues/3) [2](https://github.com/anadius/gd-efc/issues/1) in main repository you can find more information about that.
thank you for another shared drive link. i'll add it with other modifications.
